name: Feature request
description: Suggest an enhancement for parametrized_issue_template 
title: "[enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: textarea
    id: expectations
    attributes:
      label: Description
      description: A clear and concise description of the features you woul like to see
      placeholder: I wish that...
    validations:
      required: true
